In [6]:
import pandas as pd
df = pd.read_csv("/users/facsupport/asharma/Data/Preprocessed/tmp/0.csv")

In [7]:
df

,Unnamed: 0,t_0,t_1,t_2,t_3,t_4,t_5,t_6,t_7,t_8,...,providerId,payType,dayOfWeek,Mon,Tue,Wed,Thu,Fri,Sat,Sun
0,0,0.0,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.00,...,5.0,1.0,6.0,0.000000,0.000000,0.000000,0.096154,0.173077,0.000,0.000000
1,1,0.0,8.0,8.0,8.00,8.00,8.0,0.0,0.0,8.00,...,5.0,2.0,6.0,8.000000,8.000000,8.000000,8.000000,8.000000,0.000,0.615385
2,2,0.0,8.0,8.0,8.00,8.00,8.0,0.0,0.0,8.00,...,5.0,2.0,6.0,8.000000,8.000000,8.000000,8.000000,8.000000,0.000,0.615385
3,3,0.0,8.5,8.5,7.75,0.00,9.0,0.0,0.0,7.00,...,5.0,3.0,6.0,7.038462,7.326923,7.807692,5.692308,7.615385,0.000,0.000000
4,4,0.0,0.0,7.5,7.75,7.75,0.0,0.0,7.5,7.75,...,5.0,3.0,6.0,4.192308,4.711538,4.769231,5.384615,4.192308,4.625,4.211538
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2347,2347,0.0,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.00,...,4.0,1.0,6.0,0.000000,0.000000,0.588462,0.000000,0.000000,0.000,0.000000
2348,2348,0.0,0.0,0.0,7.24,5.60,4.5,0.0,0.0,0.00,...,4.0,1.0,6.0,0.384615,0.000000,0.556923,0.996923,1.345385,0.000,0.000000
2349,2349,0.0,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.00,...,4.0,1.0,6.0,0.000000,0.000000,0.000000,0.244615,0.265385,0.000,0.000000
2350,2350,0.0,0.0,0.0,2.52,2.40,0.0,0.0,0.0,2.48,...,4.0,1.0,6.0,1.837692,0.000000,1.863077,0.184615,0.006154,0.000,0.000000
2351,2351,0.0,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.00,...,4.0,1.0,6.0,0.000000,0.547692,0.000000,0.000000,0.000000,0.000,0.000000

In [11]:
for item in df.columns:
    print(item)

Unnamed: 0
t_0
t_1
t_2
t_3
t_4
t_5
t_6
t_7
t_8
t_9
t_10
t_11
t_12
t_13
t_14
t_15
t_16
t_17
t_18
t_19
t_20
t_21
t_22
t_23
t_24
t_25
t_26
t_27
t_28
t_29
t_30
t_31
t_32
t_33
t_34
t_35
t_36
t_37
t_38
t_39
t_40
t_41
t_42
t_43
t_44
t_45
t_46
t_47
t_48
t_49
t_50
t_51
t_52
t_53
t_54
t_55
t_56
t_57
t_58
t_59
t_60
t_61
t_62
t_63
t_64
t_65
t_66
t_67
t_68
t_69
t_70
t_71
t_72
t_73
t_74
t_75
t_76
t_77
t_78
t_79
t_80
t_81
t_82
t_83
t_84
t_85
t_86
t_87
t_88
t_89
f_0
f_1
f_2
f_3
f_4
f_5
f_6
f_7
f_8
f_9
f_10
f_11
f_12
f_13
f_14
f_15
f_16
f_17
f_18
f_19
f_20
f_21
f_22
f_23
f_24
f_25
f_26
f_27
f_28
f_29
f_30
f_31
f_32
f_33
f_34
f_35
f_36
f_37
f_38
f_39
f_40
f_41
f_42
f_43
f_44
f_45
f_46
f_47
f_48
f_49
f_50
f_51
f_52
f_53
f_54
f_55
f_56
f_57
f_58
f_59
f_60
f_61
f_62
f_63
f_64
f_65
f_66
f_67
f_68
f_69
f_70
f_71
f_72
f_73
f_74
f_75
f_76
f_77
f_78
f_79
f_80
f_81
f_82
f_83
f_84
f_85
f_86
f_87
f_88
f_89
jobTitle
providerId
payType
dayOfWeek
Mon
Tue
Wed
Thu
Fri
Sat
Sun